# Generated by Django 4.2.7 on 2023-12-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0003_alter_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
